### ISSUE TITLE
[FEATURE] please consider allowing configuration and/or mailto: for share 

### ISSUE THREAD

**Issue by neiljaywarner** [jhomlala/alice#116]
Please consider configuration for share.
e.g.
1) using share mailto should allow mac to work according to shareplus pub.dev site
2) allowing a default share app would be nice, and/or even a default mailto address

eg use case
1) Mac support for no worry about pipeline for preprod work
2) more easily allow for quick share to jira, share to dev email etc

Important note:
alice _does_ work on mac as is out of the box just not for share or save
share gives
MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>

save gives
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:16:20)
<asynchronous suspension>
#2      AliceSaveHelper._checkPermissions (package:alice/helper/alice_save_helper.dart:32:20)
<asynchronous suspension>

**Comment by jhomlala** [comment]
Hi there! Thanks for the suggestion.

The MissingPluginException for sharing on macOS was caused by our usage of the older share plugin. We have since migrated Alice to the modern share_plus package, which now fully supports macOS natively. The share button should now work out-of-the-box on Mac without crashing.

Regarding the feature request to add a configuration for a default mailto: address: after some testing, we've decided not to implement this for a few reasons:

URI Length Limits: HTTP logs are often very large. Stuffing the entire log body into a mailto:?body=... URI query parameter causes it to exceed the maximum URL length on many platforms/email clients, resulting in silent truncation or crashes.

Native UX: The share_plus plugin already triggers the native system share sheet. This allows you to effortlessly select whichever email client you prefer (and it will automatically handle the large text payloads correctly) without needing to configure a specific email address within Alice beforehand.

Please upgrade to the latest version of Alice to resolve the macOS sharing crash. If you run into any other issues, feel free to open a new ticket!
