### ISSUE TITLE
[BUG] Alice failed to work under dark mode

### ISSUE THREAD

**Issue by timnew** [jhomlala/alice#137]
**Describe the bug**

Inspector screen failed to when `Alice(..., darkTheme: true)`

**To Reproduce**

1. Create alice with `darkTheme: true`
2. Launch inspector

**Expected behavior**

Screen should be rendered properly

**Screenshots**
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-19 at 14 09 16](https://user-images.githubusercontent.com/1287238/213346582-2de57746-419e-4e86-b714-beddcf7bd109.png)

Log
```
#219    Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#220    StatefulElement.update
package:flutter/…/widgets/framework.dart:5082
#221    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#222    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4904
#223    Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#224    ProxyElement.update
package:flutter/…/widgets/framework.dart:5228
#225    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#226    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4904
#227    Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#228    ProxyElement.update
package:flutter/…/widgets/framework.dart:5228
#229    _InheritedNotifierElement.update
package:flutter/…/widgets/inherited_notifier.dart:107
#230    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#231    SingleChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6307
#232    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#233    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4904
#234    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:5050
#235    Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#236    StatefulElement.update
package:flutter/…/widgets/framework.dart:5082
#237    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#238    SingleChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6307
#239    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#240    SingleChildRenderObjectElement.update
package:flutter/…/widgets/framework.dart:6307
#241    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#242    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4904
#243    Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#244    ProxyElement.update
package:flutter/…/widgets/framework.dart:5228
#245    Element.updateChild
package:flutter/…/widgets/framework.dart:3570
#246    ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4904
#247    StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:5050
#248    Element.rebuild
package:flutter/…/widgets/framework.dart:4604
#249    BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2667
#250    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:882
#251    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
#252    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#253    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
#254    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#255    _invoke (dart:ui/hooks.dart:148:13)
#256    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#257    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

**Flutter doctor**
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-AU)
    • Flutter version 3.3.10 on channel stable at /Users/timnew/Workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/timnew/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 8B1B6C6A-211B-431E-9BD3-7EEBF6D33029 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Alice version**
```yml
  alice:
    dependency: "direct main"
    description:
      name: alice
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
```

**Smartphone (please complete the following information):**

Irrelevent

**Comment by timnew** [comment]
The problem is caused by these code:
https://github.com/jhomlala/alice/blob/48e5a47d5eaf48f31b5641561af5a5507bfdc3c8/lib/ui/page/alice_calls_list_screen.dart#L82-L85

When `darkTheme: true`, `aliceCore.brightness` would return `Brightness.dark`
But `ColorScheme.light` gives `Brightness.light`.

And in `ThemeData`: https://github.com/flutter/flutter/blob/6a9b2db4acb28ae565457588ab0a220f633554a6/packages/flutter/lib/src/material/theme_data.dart#L483
It requires the brightness have the consistent value.

**Comment by jhomlala** [comment]
Fixed. Please use version `0.4.1`.
