### ISSUE TITLE
Alice is crashing when app is opened from Universal/App link

### ISSUE THREAD

**Issue by DenisBronx** [jhomlala/alice#52]
Alice is currently crashing (internal crash, app keeps working without Alice notification being visible) when using app links/ universal links.

**Steps to reproduce**

1. On Android
2. Open the app
3. Open the browser and load an app link
4. Observe app opening the link (and navigating to app link page)
5. Alice notification disappears and the following stacktrace is returned
```E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.getMainActivityClass(FlutterLocalNotificationsPlugin.java:477)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:131)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:688)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:827)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:750)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9281): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9281): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference, null)
E/flutter ( 9281): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9281): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 9281): <asynchronous suspension>
E/flutter ( 9281): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 9281): #3      AndroidFlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:137:21)
E/flutter ( 9281): #4      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:136:13)
E/flutter ( 9281): #5      AliceCore._showLocalNotification (package:alice/core/alice_core.dart:175:44)
E/flutter ( 9281): #6      AliceCore._onCallsChanged (package:alice/core/alice_core.dart:75:15)
E/flutter ( 9281): #7      new AliceCore.<anonymous closure> (package:alice/core/alice_core.dart:40:55)
E/flutter ( 9281): #8      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 9281): #9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 9281): #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 9281): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 9281): #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 9281): #13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:20)
E/flutter ( 9281): #14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
E/flutter ( 9281): #15     _StartWithStreamSink._safeAddFirstEvent (package:rxdart/src/transformers/start_with.dart:56:12)
E/flutter ( 9281): #16     _StartWithStreamSink.onListen.<anonymous closure> (package:rxdart/src/transformers/start_with.dart:38:35)
E/flutter ( 9281): #17     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 9281): #18     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 9281): #19     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 9281): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 9281): #21     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 9281): #22     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 9281): #23     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 9281): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 9281): #25     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 9281): #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 9281): 
```

**Comment by jhomlala** [comment]
I've updated flutter local notification version in Alice 0.1.1.

Please try new Alice version and let me know if this bug still happens.

**Comment by DenisBronx** [comment]
@jhomlala I tried with the new version `^0.1.1` but I'm still experiencing the same issue

**Comment by jhomlala** [comment]
Can you provide some min. reproductive code? Also please add flutter doctor output.

**Comment by yourshinsuke** [comment]
AndroidFlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:137:21)

**Comment by DenisBronx** [comment]
@jhomlala I'm no longer able to reproduce the issue, I think upgrading to the latest flutter version fixed the problem
